"""Deterministic fixtures for the InvoiceAgent presentation.

Nothing in this module was extracted by OCR or generated by a live model.
The model-shaped example is a clearly labeled replay whose proposed match is
accepted only after deterministic accounting checks pass.
"""

from __future__ import annotations

from decimal import Decimal, InvalidOperation
from typing import Any, Mapping


FIXTURE_NOTICE = "Synthetic fixture replay — no OCR or live model call occurred."

CASH_SUMMARY = {
    "as_of": "2026-08-30",
    "cash_on_hand": 184_250.00,
    "receivables_30d": 73_500.00,
    "payables_30d": 41_800.00,
    "net_30d": 31_700.00,
    "overdue_receivables": 8_400.00,
    "currency": "USD",
}

PAYMENT_STORY = (
    {
        "label": "1 · Invoice arrives",
        "invoice_id": "PAPER-204",
        "party": "Acme Paper Co.",
        "total": 500.00,
        "paid": 0.00,
        "outstanding": 500.00,
        "status": "Unpaid",
        "receipts": (),
        "explanation": "The supplier asks the business for $500. This enters Accounts Payable—money going out.",
    },
    {
        "label": "2 · Pay $300",
        "invoice_id": "PAPER-204",
        "party": "Acme Paper Co.",
        "total": 500.00,
        "paid": 300.00,
        "outstanding": 200.00,
        "status": "Partial",
        "receipts": (("PAY-781", 300.00),),
        "explanation": "Receipt PAY-781 proves $300 moved. The invoice still has $200 left to pay.",
    },
    {
        "label": "3 · Pay final $200",
        "invoice_id": "PAPER-204",
        "party": "Acme Paper Co.",
        "total": 500.00,
        "paid": 500.00,
        "outstanding": 0.00,
        "status": "Paid",
        "receipts": (("PAY-781", 300.00), ("PAY-799", 200.00)),
        "explanation": "Receipt PAY-799 proves the final $200 moved. The outstanding balance is now exactly $0.",
    },
)

LEDGER = [
    {
        "kind": "AR",
        "invoice_id": "INV-2041",
        "party": "Tycho Mining Cooperative",
        "due": "2026-09-04",
        "amount": 36_000.00,
        "payment_ref": "PAY-901",
        "reconciliation": "Matched",
        "cash_status": "Received",
    },
    {
        "kind": "AP",
        "invoice_id": "MB-884",
        "party": "Lunar Relay Supplies",
        "due": "2026-09-02",
        "amount": 12_840.00,
        "payment_ref": "MB-884",
        "reconciliation": "Matched",
        "cash_status": "Scheduled",
    },
    {
        "kind": "AP",
        "invoice_id": "NLS-338",
        "party": "Northstar Life Support",
        "due": "2026-09-07",
        "amount": 6_420.00,
        "payment_ref": "NLS-338",
        "reconciliation": "Matched after local extraction",
        "cash_status": "Scheduled",
    },
    {
        "kind": "AR",
        "invoice_id": "INV-2050",
        "party": "Artemis Surface Lab",
        "due": "2026-09-12",
        "amount": 29_100.00,
        "payment_ref": "—",
        "reconciliation": "Open",
        "cash_status": "Expected",
    },
    {
        "kind": "AR",
        "invoice_id": "Q-771",
        "party": "Mare Imbrium Freight",
        "due": "2026-08-27",
        "amount": 8_400.00,
        "payment_ref": "Two candidates",
        "reconciliation": "Needs review",
        "cash_status": "Overdue",
    },
    {
        "kind": "AP",
        "invoice_id": "SOL-190",
        "party": "Sunline Power Systems",
        "due": "2026-09-18",
        "amount": 22_540.00,
        "payment_ref": "—",
        "reconciliation": "Open",
        "cash_status": "Planned",
    },
]


SCENARIOS = {
    "easy-local": {
        "id": "easy-local",
        "short_label": "Easy · local accept",
        "title": "Exact references never need a model",
        "eyebrow": "Scenario 1 of 3 · deterministic fixture",
        "fixture_notice": FIXTURE_NOTICE,
        "route": "local",
        "decision": "Accepted locally",
        "decision_tone": "good",
        "summary": (
            "The invoice number, vendor, amount, and payment reference agree. "
            "Plain accounting rules reconcile it immediately."
        ),
        "invoice": {
            "invoice_id": "MB-884",
            "party": "Lunar Relay Supplies",
            "amount": 12_840.00,
            "due": "2026-09-02",
            "direction": "AP",
        },
        "payment": {
            "reference": "MB-884",
            "party": "Lunar Relay Supplies",
            "amount": 12_840.00,
            "date": "2026-08-30",
        },
        "checks": [
            {"label": "Invoice reference", "value": "Exact match", "passed": True},
            {"label": "Amount difference", "value": "$0.00", "passed": True},
            {"label": "Known counterparty", "value": "Yes", "passed": True},
        ],
        "steps": [
            "Load the prewritten invoice and payment fixture.",
            "Compare identifiers, party, currency, and amount.",
            "Write a reconciliation record; no model is invoked.",
        ],
        "model_replay": None,
        "why": "Fast, cheap, and fully explainable. Rules should keep the easy work.",
    },
    "model-accept": {
        "id": "model-accept",
        "short_label": "Fuzzy · verified suggestion",
        "title": "The small document specialist finds the invoice number",
        "eyebrow": "Scenario 2 of 3 · recorded extraction replay",
        "fixture_notice": FIXTURE_NOTICE,
        "route": "small_model",
        "decision": "Invoice number extracted locally",
        "decision_tone": "model",
        "summary": (
            "The invoice uses an unfamiliar layout that the label rule misses. A replayed "
            "LayoutLMv3 result selects NLS-338, then hard checks match the payment reference, "
            "amount, party, and date."
        ),
        "invoice": {
            "invoice_id": "NLS-338",
            "party": "Northstar Life Support",
            "amount": 6_420.00,
            "due": "2026-09-07",
            "direction": "AP",
        },
        "payment": {
            "reference": "NLS-338",
            "party": "Northstar Life Support LLC",
            "amount": 6_420.00,
            "date": "2026-08-29",
        },
        "checks": [
            {"label": "Invoice-ID entity span", "value": "NLS-338 · 0.94", "passed": True},
            {"label": "Payment reference", "value": "Exact match", "passed": True},
            {"label": "Amount difference", "value": "$0.00", "passed": True},
        ],
        "steps": [
            "The anchored rule cannot locate an invoice-number label in the unusual layout.",
            "Replay the fixture's recorded LayoutLMv3 invoice-number token span.",
            "Match that extracted ID to the receipt, then verify party, amount, and dates.",
        ],
        "model_replay": {
            "label": "invoice_number = NLS-338",
            "confidence": 0.94,
            "evidence": "Selected OCR tokens: NLS · - · 338; entity confidence only",
            "provenance": "Stored demo fixture; not generated in this session",
        },
        "why": "The small model reads one narrow field. Deterministic accounting checks still decide whether a receipt may change the balance.",
    },
    "ambiguous-escalate": {
        "id": "ambiguous-escalate",
        "short_label": "Ambiguous · escalate",
        "title": "Two plausible payments means stop, not guess",
        "eyebrow": "Scenario 3 of 3 · fail-closed fixture",
        "fixture_notice": FIXTURE_NOTICE,
        "route": "escalate",
        "decision": "Escalated for review",
        "decision_tone": "warn",
        "summary": (
            "Two same-value transfers could settle the overdue invoice, and neither carries "
            "a decisive reference. The system preserves both candidates for a person."
        ),
        "invoice": {
            "invoice_id": "Q-771",
            "party": "Mare Imbrium Freight",
            "amount": 8_400.00,
            "due": "2026-08-27",
            "direction": "AR",
        },
        "payment": {
            "reference": "TRX-441 or TRX-447",
            "party": "MIF Operations / Mare Freight",
            "amount": 8_400.00,
            "date": "2026-08-28 / 2026-08-29",
        },
        "checks": [
            {"label": "Plausible candidates", "value": "2", "passed": False},
            {"label": "Unique reference", "value": "Missing", "passed": False},
            {"label": "Amount difference", "value": "$0.00 each", "passed": True},
        ],
        "steps": [
            "Rules identify two equally valued candidate payments.",
            "A recorded score cannot separate them with sufficient confidence.",
            "Create one review item containing both candidates and all evidence.",
        ],
        "model_replay": {
            "label": "ambiguous",
            "confidence": 0.53,
            "evidence": "Both counterparty names are plausible aliases",
            "provenance": "Stored demo fixture; not generated in this session",
        },
        "why": "A useful agent knows when evidence is insufficient. Escalation is a successful outcome.",
    },
}

SCENARIO_ORDER = ("easy-local", "model-accept", "ambiguous-escalate")


def _money(value: Any) -> Decimal | None:
    """Return exact positive money, or None for invalid structured input."""

    if isinstance(value, bool) or isinstance(value, float):
        return None
    try:
        number = Decimal(str(value))
    except (InvalidOperation, TypeError, ValueError):
        return None
    if not number.is_finite() or number <= 0 or number.as_tuple().exponent < -2:
        return None
    return number.quantize(Decimal("0.01"))


def route_structured_entry(entry: Mapping[str, Any]) -> dict[str, Any]:
    """Route a manually entered pair without OCR or a model call.

    Exact evidence is accepted locally. A same-value, known-party pair without
    an exact reference is marked as *needing* a model; the fallback does not
    fabricate a model response. Everything else fails closed to review.
    """

    invoice_amount = _money(entry.get("invoice_amount"))
    payment_amount = _money(entry.get("payment_amount"))
    invoice_id = str(entry.get("invoice_id") or "").strip()
    payment_reference = str(entry.get("payment_reference") or "").strip()
    known_party = entry.get("known_party") is True

    if invoice_amount is None or payment_amount is None or not invoice_id:
        return {
            "route": "escalate",
            "decision": "Incomplete structured entry",
            "accepted": False,
            "model_called": False,
            "reason": "Add a valid invoice ID and non-negative invoice and payment amounts.",
        }

    amount_matches = invoice_amount == payment_amount
    reference_matches = bool(payment_reference) and payment_reference.casefold() == invoice_id.casefold()

    if amount_matches and reference_matches and known_party:
        return {
            "route": "local",
            "decision": "Accepted locally",
            "accepted": True,
            "model_called": False,
            "reason": "Known party, exact reference, and exact amount all agree.",
        }

    if amount_matches and known_party:
        return {
            "route": "escalate",
            "decision": "Payment reference needs review",
            "accepted": False,
            "model_called": False,
            "reason": (
                "The amount and party agree, but the payment reference does not. Ryan's model "
                "extracts invoice numbers; it does not invent a missing payment reference, so "
                "the entry remains unposted."
            ),
        }

    return {
        "route": "escalate",
        "decision": "Escalated for review",
        "accepted": False,
        "model_called": False,
        "reason": "The structured evidence conflicts or is too weak for automatic reconciliation.",
    }
